---
    name: ci
    on:
      push:
        branches:
          - master
    
    jobs:
      delete_previous_release:
        name: Delete previous Development Release
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - uses: actions/checkout@v4
          - run: gh release delete latest --cleanup-tag -y 
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      draft_release:
        name: Create Release
        runs-on: ubuntu-latest
        continue-on-error: false
        needs: delete_previous_release
        outputs:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
          - uses: actions/checkout@v4
          - name: Create Release
            id: create_release
            uses: ncipollo/release-action@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              body: This is based on the latest commit.
              tag: latest
              name: "Development release"
              draft: false
              prerelease: true
    
      mxe64:
        name: Windows 64-bit (MXE Cross Build)
        runs-on: windows-latest
        defaults:
          run:
            shell: msys2 {0}
        continue-on-error: false
        needs: draft_release
        env:
          CFLAGS: -std=c11
          CXXFLAGS: -std=c++14
        steps:
          - uses: actions/checkout@v4
    
          - name: Setup MSYS2
            uses: msys2/setup-msys2@v2
            with:
              msystem: mingw64
              update: true
              install: mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-pango mingw-w64-x86_64-rtmpdump mingw-w64-x86_64-glew mingw-w64-x86_64-SDL2 mingw-w64-x86_64-cmake mingw-w64-x86_64-nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-upx mingw-w64-x86_64-7zip intltool mingw-w64-x86_64-libtool mingw-w64-x86_64-gperf mingw-w64-x86_64-nsis git 
    
          - name: Run MXE Build
            run: |
              cmake .
              ninja
              sed -i -e "s/Lightspark Team/The Lightspark Developers/g" CPackConfig.cmake
              cp /mingw64/bin/libgcc_s_seh-1.dll \
              /mingw64/bin/SDL2.dll \
              /mingw64/bin/libglib-2.0-0.dll \
              /mingw64/bin/libintl-8.dll \
              /mingw64/bin/libwinpthread-1.dll \
              /mingw64/bin/libpcre2-8-0.dll \
              /mingw64/bin/libstdc++-6.dll \
              /mingw64/bin/avcodec-60.dll \
              /mingw64/bin/avformat-60.dll \
              /mingw64/bin/avutil-58.dll \
              /mingw64/bin/libcairo-2.dll \
              /mingw64/bin/libcurl-4.dll \
              /mingw64/bin/liblzma-5.dll \
              /mingw64/bin/libgobject-2.0-0.dll \
              /mingw64/bin/libpango-1.0-0.dll \
              /mingw64/bin/libpangocairo-1.0-0.dll \
              /mingw64/bin/librtmp-1.dll \
              /mingw64/bin/swresample-4.dll \
              /mingw64/bin/libjpeg-8.dll \
              /mingw64/bin/libpng16-16.dll \
              /mingw64/bin/zlib1.dll \
              /mingw64/bin/glew32.dll \
              /mingw64/bin/libiconv-2.dll \
              /mingw64/bin/libaom.dll \
              /mingw64/bin/libdav1d-7.dll \
              /mingw64/bin/libgsm.dll \
              /mingw64/bin/libjxl.dll \
              /mingw64/bin/libjxl_threads.dll \
              /mingw64/bin/libmp3lame-0.dll \
              /mingw64/bin/libopencore-amrnb-0.dll \
              /mingw64/bin/libopenjp2-7.dll \
              /mingw64/bin/libopencore-amrwb-0.dll \
              /mingw64/bin/libopus-0.dll \
              /mingw64/bin/libspeex-1.dll \
              /mingw64/bin/librsvg-2-2.dll \
              /mingw64/bin/libSvtAv1Enc-2.dll \
              /mingw64/bin/libtheoradec-1.dll \
              /mingw64/bin/libtheoraenc-1.dll \
              /mingw64/bin/libva.dll \
              /mingw64/bin/libvorbisenc-2.dll \
              /mingw64/bin/libvpl.dll \
              /mingw64/bin/rav1e.dll \
              /mingw64/bin/libvpx-1.dll \
              /mingw64/bin/libwebp-7.dll \
              /mingw64/bin/libwebpmux-3.dll \
              /mingw64/bin/libx264-164.dll \
              /mingw64/bin/xvidcore.dll \
              /mingw64/bin/libx265.dll \
              /mingw64/bin/libzvbi-0.dll \
              /mingw64/bin/libbz2-1.dll \
              /mingw64/bin/libbluray-2.dll \
              /mingw64/bin/libgme.dll \
              /mingw64/bin/libmodplug-1.dll \
              /mingw64/bin/libgnutls-30.dll \
              /mingw64/bin/libvorbis-0.dll \
              /mingw64/bin/libsrt.dll \
              /mingw64/bin/libssh.dll \
              /mingw64/bin/libva_win32.dll \
              /mingw64/bin/libfreetype-6.dll \
              /mingw64/bin/libxml2-2.dll \
              /mingw64/bin/libfontconfig-1.dll \
              /mingw64/bin/libpixman-1-0.dll \
              /mingw64/bin/libbrotlidec.dll \
              /mingw64/bin/libidn2-0.dll \
              /mingw64/bin/libnghttp2-14.dll \
              /mingw64/bin/libpsl-5.dll \
              /mingw64/bin/libssh2-1.dll \
              /mingw64/bin/libssl-3-x64.dll \
              /mingw64/bin/libzstd.dll \
              /mingw64/bin/libffi-8.dll \
              /mingw64/bin/libfribidi-0.dll \
              /mingw64/bin/libcrypto-3-x64.dll \
              /mingw64/bin/libgio-2.0-0.dll \
              /mingw64/bin/libthai-0.dll \
              /mingw64/bin/libharfbuzz-0.dll \
              /mingw64/bin/libpangoft2-1.0-0.dll \
              /mingw64/bin/libpangowin32-1.0-0.dll \
              /mingw64/bin/libhogweed-6.dll \
              /mingw64/bin/libgmp-10.dll \
              /mingw64/bin/libnettle-8.dll \
              /mingw64/bin/libsoxr.dll \
              /mingw64/bin/libbrotlienc.dll \
              /mingw64/bin/libhwy.dll \
              /mingw64/bin/libcairo-gobject-2.dll \
              /mingw64/bin/libjxl_cms.dll \
              /mingw64/bin/libgdk_pixbuf-2.0-0.dll \
              /mingw64/bin/libogg-0.dll \
              /mingw64/bin/libsharpyuv-0.dll \
              /mingw64/bin/libtasn1-6.dll \
              /mingw64/bin/libunistring-5.dll \
              /mingw64/bin/libp11-kit-0.dll \
              /mingw64/bin/libexpat-1.dll \
              /mingw64/bin/libbrotlicommon.dll \
              /mingw64/bin/libdatrie-1.dll \
              /mingw64/bin/libgmodule-2.0-0.dll \
              /mingw64/bin/libgraphite2.dll \
              /mingw64/bin/libgomp-1.dll \
              /mingw64/bin/liblcms2-2.dll \AMD64/RelWithDebInfo/bin
              ninja package
              mv -v Lightspark*exe Lightspark-v-Installer-win64.exe
    
          - name: Upload Installer Release Asset
            uses: softprops/action-gh-release@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: latest
              files: Lightspark-v-Installer-win64.exe
    
      mxe32:
        name: Windows 32-bit
        runs-on: windows-latest
        defaults:
          run:
            shell: msys2 {0}
        continue-on-error: false
        needs: draft_release
        env:
          CFLAGS: -std=c11
          CXXFLAGS: -std=c++14
        steps:
          - uses: actions/checkout@v4
    
          - name: Setup MSYS2
            uses: msys2/setup-msys2@v2
            with:
              msystem: mingw32
              update: true
              install: mingw-w64-i686-ffmpeg mingw-w64-i686-pango mingw-w64-i686-rtmpdump mingw-w64-i686-glew mingw-w64-i686-SDL2 mingw-w64-i686-cmake mingw-w64-i686-nasm mingw-w64-i686-gcc mingw-w64-i686-upx p7zip intltool mingw-w64-i686-libtool mingw-w64-i686-gperf mingw-w64-i686-nsis git 
    
          - name: Run MXE Build
            run: |
              cmake .
              ninja
              sed -i -e "s/Lightspark Team/The Lightspark Developers/g" CPackConfig.cmake
              cp /mingw64/bin/libgcc_s_seh-1.dll \
              /mingw64/bin/SDL2.dll \
              /mingw64/bin/libglib-2.0-0.dll \
              /mingw64/bin/libintl-8.dll \
              /mingw64/bin/libwinpthread-1.dll \
              /mingw64/bin/libpcre2-8-0.dll \
              /mingw64/bin/libstdc++-6.dll \
              /mingw64/bin/avcodec-60.dll \
              /mingw64/bin/avformat-60.dll \
              /mingw64/bin/avutil-58.dll \
              /mingw64/bin/libcairo-2.dll \
              /mingw64/bin/libcurl-4.dll \
              /mingw64/bin/liblzma-5.dll \
              /mingw64/bin/libgobject-2.0-0.dll \
              /mingw64/bin/libpango-1.0-0.dll \
              /mingw64/bin/libpangocairo-1.0-0.dll \
              /mingw64/bin/librtmp-1.dll \
              /mingw64/bin/swresample-4.dll \
              /mingw64/bin/libjpeg-8.dll \
              /mingw64/bin/libpng16-16.dll \
              /mingw64/bin/zlib1.dll \
              /mingw64/bin/glew32.dll \
              /mingw64/bin/libiconv-2.dll \
              /mingw64/bin/libaom.dll \
              /mingw64/bin/libdav1d-7.dll \
              /mingw64/bin/libgsm.dll \
              /mingw64/bin/libjxl.dll \
              /mingw64/bin/libjxl_threads.dll \
              /mingw64/bin/libmp3lame-0.dll \
              /mingw64/bin/libopencore-amrnb-0.dll \
              /mingw64/bin/libopenjp2-7.dll \
              /mingw64/bin/libopencore-amrwb-0.dll \
              /mingw64/bin/libopus-0.dll \
              /mingw64/bin/libspeex-1.dll \
              /mingw64/bin/librsvg-2-2.dll \
              /mingw64/bin/libSvtAv1Enc-2.dll \
              /mingw64/bin/libtheoradec-1.dll \
              /mingw64/bin/libtheoraenc-1.dll \
              /mingw64/bin/libva.dll \
              /mingw64/bin/libvorbisenc-2.dll \
              /mingw64/bin/libvpl.dll \
              /mingw64/bin/rav1e.dll \
              /mingw64/bin/libvpx-1.dll \
              /mingw64/bin/libwebp-7.dll \
              /mingw64/bin/libwebpmux-3.dll \
              /mingw64/bin/libx264-164.dll \
              /mingw64/bin/xvidcore.dll \
              /mingw64/bin/libx265.dll \
              /mingw64/bin/libzvbi-0.dll \
              /mingw64/bin/libbz2-1.dll \
              /mingw64/bin/libbluray-2.dll \
              /mingw64/bin/libgme.dll \
              /mingw64/bin/libmodplug-1.dll \
              /mingw64/bin/libgnutls-30.dll \
              /mingw64/bin/libvorbis-0.dll \
              /mingw64/bin/libsrt.dll \
              /mingw64/bin/libssh.dll \
              /mingw64/bin/libva_win32.dll \
              /mingw64/bin/libfreetype-6.dll \
              /mingw64/bin/libxml2-2.dll \
              /mingw64/bin/libfontconfig-1.dll \
              /mingw64/bin/libpixman-1-0.dll \
              /mingw64/bin/libbrotlidec.dll \
              /mingw64/bin/libidn2-0.dll \
              /mingw64/bin/libnghttp2-14.dll \
              /mingw64/bin/libpsl-5.dll \
              /mingw64/bin/libssh2-1.dll \
              /mingw64/bin/libssl-3-x64.dll \
              /mingw64/bin/libzstd.dll \
              /mingw64/bin/libffi-8.dll \
              /mingw64/bin/libfribidi-0.dll \
              /mingw64/bin/libcrypto-3-x64.dll \
              /mingw64/bin/libgio-2.0-0.dll \
              /mingw64/bin/libthai-0.dll \
              /mingw64/bin/libharfbuzz-0.dll \
              /mingw64/bin/libpangoft2-1.0-0.dll \
              /mingw64/bin/libpangowin32-1.0-0.dll \
              /mingw64/bin/libhogweed-6.dll \
              /mingw64/bin/libgmp-10.dll \
              /mingw64/bin/libnettle-8.dll \
              /mingw64/bin/libsoxr.dll \
              /mingw64/bin/libbrotlienc.dll \
              /mingw64/bin/libhwy.dll \
              /mingw64/bin/libcairo-gobject-2.dll \
              /mingw64/bin/libjxl_cms.dll \
              /mingw64/bin/libgdk_pixbuf-2.0-0.dll \
              /mingw64/bin/libogg-0.dll \
              /mingw64/bin/libsharpyuv-0.dll \
              /mingw64/bin/libtasn1-6.dll \
              /mingw64/bin/libunistring-5.dll \
              /mingw64/bin/libp11-kit-0.dll \
              /mingw64/bin/libexpat-1.dll \
              /mingw64/bin/libbrotlicommon.dll \
              /mingw64/bin/libdatrie-1.dll \
              /mingw64/bin/libgmodule-2.0-0.dll \
              /mingw64/bin/libgraphite2.dll \
              /mingw64/bin/libgomp-1.dll \
              /mingw64/bin/liblcms2-2.dll \AMD64/RelWithDebInfo/bin
              ninja package
              mv -v Lightspark*exe Lightspark-v-Installer-win32.exe
    
          - name: Upload Installer Release Asset
            uses: softprops/action-gh-release@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: latest
              files: Lightspark-v-Installer-win32.exe
    
